#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace demo
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="demoBTLWEB")]
	public partial class demoDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertdangnhap_dangky(dangnhap_dangky instance);
    partial void Updatedangnhap_dangky(dangnhap_dangky instance);
    partial void Deletedangnhap_dangky(dangnhap_dangky instance);
    #endregion
		
		public demoDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["demoBTLWEBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public demoDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public demoDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public demoDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public demoDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DangNhap> DangNhaps
		{
			get
			{
				return this.GetTable<DangNhap>();
			}
		}
		
		public System.Data.Linq.Table<dangnhap_dangky> dangnhap_dangkies
		{
			get
			{
				return this.GetTable<dangnhap_dangky>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DangNhap_insert")]
		public int DangNhap_insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string taikhoan, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string matkhau)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), taikhoan, matkhau);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.DangNhap_search")]
		public ISingleResult<DangNhap_searchResult> DangNhap_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string taikhoan, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string matkhau)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), taikhoan, matkhau);
			return ((ISingleResult<DangNhap_searchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.dangnhap_dangky_insert")]
		public int dangnhap_dangky_insert([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string staikhoan, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string smatkhau, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string semail, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(10)")] string sSDT, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string sDiachi)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), staikhoan, smatkhau, semail, sSDT, sDiachi);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.dangnhap_dangky_search")]
		public ISingleResult<dangnhap_dangky_searchResult> dangnhap_dangky_search([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string staikhoan, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string smatkhau)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), staikhoan, smatkhau);
			return ((ISingleResult<dangnhap_dangky_searchResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pr_timTTsdt")]
		public ISingleResult<pr_timTTsdtResult> pr_timTTsdt([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(10)")] string sSDT)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sSDT);
			return ((ISingleResult<pr_timTTsdtResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DangNhap")]
	public partial class DangNhap
	{
		
		private int _IDName;
		
		private string _taiKhoan;
		
		private string _matKhau;
		
		public DangNhap()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDName", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int IDName
		{
			get
			{
				return this._IDName;
			}
			set
			{
				if ((this._IDName != value))
				{
					this._IDName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taiKhoan", DbType="NVarChar(50)")]
		public string taiKhoan
		{
			get
			{
				return this._taiKhoan;
			}
			set
			{
				if ((this._taiKhoan != value))
				{
					this._taiKhoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="NVarChar(50)")]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this._matKhau = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dangnhap_dangky")]
	public partial class dangnhap_dangky : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _iMaKH;
		
		private string _sTaiKhoan;
		
		private string _sMatkhau;
		
		private string _sEmail;
		
		private string _sSDT;
		
		private string _sDiachi;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OniMaKHChanging(int value);
    partial void OniMaKHChanged();
    partial void OnsTaiKhoanChanging(string value);
    partial void OnsTaiKhoanChanged();
    partial void OnsMatkhauChanging(string value);
    partial void OnsMatkhauChanged();
    partial void OnsEmailChanging(string value);
    partial void OnsEmailChanged();
    partial void OnsSDTChanging(string value);
    partial void OnsSDTChanged();
    partial void OnsDiachiChanging(string value);
    partial void OnsDiachiChanged();
    #endregion
		
		public dangnhap_dangky()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iMaKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int iMaKH
		{
			get
			{
				return this._iMaKH;
			}
			set
			{
				if ((this._iMaKH != value))
				{
					this.OniMaKHChanging(value);
					this.SendPropertyChanging();
					this._iMaKH = value;
					this.SendPropertyChanged("iMaKH");
					this.OniMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTaiKhoan", DbType="NVarChar(50)")]
		public string sTaiKhoan
		{
			get
			{
				return this._sTaiKhoan;
			}
			set
			{
				if ((this._sTaiKhoan != value))
				{
					this.OnsTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._sTaiKhoan = value;
					this.SendPropertyChanged("sTaiKhoan");
					this.OnsTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sMatkhau", DbType="NVarChar(50)")]
		public string sMatkhau
		{
			get
			{
				return this._sMatkhau;
			}
			set
			{
				if ((this._sMatkhau != value))
				{
					this.OnsMatkhauChanging(value);
					this.SendPropertyChanging();
					this._sMatkhau = value;
					this.SendPropertyChanged("sMatkhau");
					this.OnsMatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sEmail", DbType="NVarChar(50)")]
		public string sEmail
		{
			get
			{
				return this._sEmail;
			}
			set
			{
				if ((this._sEmail != value))
				{
					this.OnsEmailChanging(value);
					this.SendPropertyChanging();
					this._sEmail = value;
					this.SendPropertyChanged("sEmail");
					this.OnsEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sSDT", DbType="NVarChar(10)")]
		public string sSDT
		{
			get
			{
				return this._sSDT;
			}
			set
			{
				if ((this._sSDT != value))
				{
					this.OnsSDTChanging(value);
					this.SendPropertyChanging();
					this._sSDT = value;
					this.SendPropertyChanged("sSDT");
					this.OnsSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sDiachi", DbType="NVarChar(50)")]
		public string sDiachi
		{
			get
			{
				return this._sDiachi;
			}
			set
			{
				if ((this._sDiachi != value))
				{
					this.OnsDiachiChanging(value);
					this.SendPropertyChanging();
					this._sDiachi = value;
					this.SendPropertyChanged("sDiachi");
					this.OnsDiachiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class DangNhap_searchResult
	{
		
		private int _IDName;
		
		private string _taiKhoan;
		
		private string _matKhau;
		
		public DangNhap_searchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDName", DbType="Int NOT NULL")]
		public int IDName
		{
			get
			{
				return this._IDName;
			}
			set
			{
				if ((this._IDName != value))
				{
					this._IDName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taiKhoan", DbType="NVarChar(50)")]
		public string taiKhoan
		{
			get
			{
				return this._taiKhoan;
			}
			set
			{
				if ((this._taiKhoan != value))
				{
					this._taiKhoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", DbType="NVarChar(50)")]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this._matKhau = value;
				}
			}
		}
	}
	
	public partial class dangnhap_dangky_searchResult
	{
		
		private int _iMaKH;
		
		private string _sTaiKhoan;
		
		private string _sMatkhau;
		
		private string _sEmail;
		
		private string _sSDT;
		
		private string _sDiachi;
		
		public dangnhap_dangky_searchResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_iMaKH", DbType="Int NOT NULL")]
		public int iMaKH
		{
			get
			{
				return this._iMaKH;
			}
			set
			{
				if ((this._iMaKH != value))
				{
					this._iMaKH = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTaiKhoan", DbType="NVarChar(50)")]
		public string sTaiKhoan
		{
			get
			{
				return this._sTaiKhoan;
			}
			set
			{
				if ((this._sTaiKhoan != value))
				{
					this._sTaiKhoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sMatkhau", DbType="NVarChar(50)")]
		public string sMatkhau
		{
			get
			{
				return this._sMatkhau;
			}
			set
			{
				if ((this._sMatkhau != value))
				{
					this._sMatkhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sEmail", DbType="NVarChar(50)")]
		public string sEmail
		{
			get
			{
				return this._sEmail;
			}
			set
			{
				if ((this._sEmail != value))
				{
					this._sEmail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sSDT", DbType="NVarChar(10)")]
		public string sSDT
		{
			get
			{
				return this._sSDT;
			}
			set
			{
				if ((this._sSDT != value))
				{
					this._sSDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sDiachi", DbType="NVarChar(50)")]
		public string sDiachi
		{
			get
			{
				return this._sDiachi;
			}
			set
			{
				if ((this._sDiachi != value))
				{
					this._sDiachi = value;
				}
			}
		}
	}
	
	public partial class pr_timTTsdtResult
	{
		
		private string _sHoten;
		
		private string _sTenphim;
		
		private string _sGioxem;
		
		public pr_timTTsdtResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sHoten", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string sHoten
		{
			get
			{
				return this._sHoten;
			}
			set
			{
				if ((this._sHoten != value))
				{
					this._sHoten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sTenphim", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string sTenphim
		{
			get
			{
				return this._sTenphim;
			}
			set
			{
				if ((this._sTenphim != value))
				{
					this._sTenphim = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sGioxem", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string sGioxem
		{
			get
			{
				return this._sGioxem;
			}
			set
			{
				if ((this._sGioxem != value))
				{
					this._sGioxem = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
